INSERT INTO Locations VALUES(0,'Slotteatha',5);
INSERT INTO Locations VALUES(1,'Fealophere',4);
INSERT INTO Locations VALUES(2,'Ocheryon',3);
INSERT INTO Locations VALUES(3,'Aewedell',1);
INSERT INTO Locations VALUES(4,'Eaphidolon',1);
INSERT INTO Locations VALUES(5,'The Fortune Lake',1);
INSERT INTO Locations VALUES(6,'The All Lands',0);
INSERT INTO Locations VALUES(7,'The Ancestor Territory',5);
INSERT INTO Locations VALUES(8,'The Sanguine Reach',4);
INSERT INTO Locations VALUES(9,'The Conjured Country',0);
INSERT INTO Locations VALUES(10,'Iokaghar',0);
INSERT INTO Locations VALUES(11,'Giostiamos',4);
INSERT INTO Locations VALUES(12,'Stemiamel',3);
INSERT INTO Locations VALUES(13,'Greddorus',1);
INSERT INTO Locations VALUES(14,'Eattinata',5);
INSERT INTO Locations VALUES(15,'The Mad Moon',4);
INSERT INTO Locations VALUES(16,'The White Sea',3);
INSERT INTO Locations VALUES(17,'The Parallel Country',1);
INSERT INTO Locations VALUES(18,'The Ancestor Plane',5);
INSERT INTO Locations VALUES(19,'The Tempest Expanse',3);
INSERT INTO Locations VALUES(20,'Zeomilas',4);
INSERT INTO Locations VALUES(21,'Flallarath',3);
INSERT INTO Locations VALUES(22,'Haclique',4);
INSERT INTO Locations VALUES(23,'Iogreogus',3);
INSERT INTO Locations VALUES(24,'Qekaspea',1);
INSERT INTO Locations VALUES(25,'The Cosmic Vales',5);
INSERT INTO Locations VALUES(26,'The Fate Nexus',4);
INSERT INTO Locations VALUES(27,'The Empty Plane',1);
INSERT INTO Locations VALUES(28,'The Ethereal Territory',5);
INSERT INTO Locations VALUES(29,'The Illusion Moon',5);
INSERT INTO Locations VALUES(30,'Dreaceodale',2);
INSERT INTO Locations VALUES(31,'Yeadrumelan',0);
INSERT INTO Locations VALUES(32,'Eabbaxus',1);
INSERT INTO Locations VALUES(33,'Gepheodu',2);
INSERT INTO Locations VALUES(34,'Aegleobis',5);
INSERT INTO Locations VALUES(35,'The Nimbus Province',2);
INSERT INTO Locations VALUES(36,'The Bone Sanctuary',3);
INSERT INTO Locations VALUES(37,'The Forsaken World',1);
INSERT INTO Locations VALUES(38,'The Arctic Nation',2);
INSERT INTO Locations VALUES(39,'The Miniature Lake',5);
INSERT INTO Locations VALUES(40,'Iostirant',1);
INSERT INTO Locations VALUES(41,'Turrioque',2);
INSERT INTO Locations VALUES(42,'Pheoxughar',4);
INSERT INTO Locations VALUES(43,'Juppeatuary',0);
INSERT INTO Locations VALUES(44,'Qearriorial',2);
INSERT INTO Locations VALUES(45,'The Sanguine Yonder',0);
INSERT INTO Locations VALUES(46,'The Severed Sea',1);
INSERT INTO Locations VALUES(47,'The Transient Earth',5);
INSERT INTO Locations VALUES(48,'The Crimson Empire',0);
INSERT INTO Locations VALUES(49,'The Hallowed Isle',5);
INSERT INTO Locations VALUES(50,'Sioglalyn',3);
INSERT INTO Locations VALUES(51,'Gommala',1);
INSERT INTO Locations VALUES(52,'Feabbophere',2);
INSERT INTO Locations VALUES(53,'Chiorotopia',0);
INSERT INTO Locations VALUES(54,'Siasheanary',3);
INSERT INTO Locations VALUES(55,'The Gentle Moon',0);
INSERT INTO Locations VALUES(56,'The Living Isles',0);
INSERT INTO Locations VALUES(57,'The Twin Planet',2);
INSERT INTO Locations VALUES(58,'The Demi Expanse',2);
INSERT INTO Locations VALUES(59,'The Void Nexus',2);
INSERT INTO Locations VALUES(60,'Oqepia',2);
INSERT INTO Locations VALUES(61,'Qussithis',1);
INSERT INTO Locations VALUES(62,'Opeoroth',5);
INSERT INTO Locations VALUES(63,'Iakeanys',5);
INSERT INTO Locations VALUES(64,'Fleodalar',1);
INSERT INTO Locations VALUES(65,'The Ebon Expanse',1);
INSERT INTO Locations VALUES(66,'The Harsh Lake',4);
INSERT INTO Locations VALUES(67,'The Final World',0);
INSERT INTO Locations VALUES(68,'The Magic Lands',0);
INSERT INTO Locations VALUES(69,'Eocriotika',0);
INSERT INTO Locations VALUES(70,'Glealliotion',4);
INSERT INTO Locations VALUES(71,'Stiaveatia',3);
INSERT INTO Locations VALUES(72,'Yaeklanem',3);
INSERT INTO Locations VALUES(73,'Blopivar',4);
INSERT INTO Locations VALUES(74,'The Fractioned Reach',0);
INSERT INTO Locations VALUES(75,'The Mammoth Valley',3);
INSERT INTO Locations VALUES(76,'The Paralyzed Ocean',2);
INSERT INTO Locations VALUES(77,'The Echo Reach',0);
INSERT INTO Locations VALUES(78,'The Ethereal Domain',1);
INSERT INTO Locations VALUES(79,'Iglitope',3);
INSERT INTO Locations VALUES(80,'Istrethan',3);
INSERT INTO Locations VALUES(81,'Nunnirea',3);
INSERT INTO Locations VALUES(82,'Clommiarus',2);
INSERT INTO Locations VALUES(83,'Feggiomos',4);
INSERT INTO Locations VALUES(84,'The Whole Vales',4);
INSERT INTO Locations VALUES(85,'The Twin Vales',3);
INSERT INTO Locations VALUES(86,'The Mirage Isle',2);
INSERT INTO Locations VALUES(87,'The Cinder Country',5);
INSERT INTO Locations VALUES(88,'The Harsh Realms',0);
INSERT INTO Locations VALUES(89,'Waeglioron',5);
INSERT INTO Locations VALUES(90,'Yaecliran',2);
INSERT INTO Locations VALUES(91,'Aelluchaeus',0);
INSERT INTO Locations VALUES(92,'Aecaria',0);
INSERT INTO Locations VALUES(93,'Preagemel',5);
INSERT INTO Locations VALUES(94,'The Ancient Territory',0);
INSERT INTO Locations VALUES(95,'The Inferno Fields',1);
INSERT INTO Locations VALUES(96,'The Ageless Forest',4);
INSERT INTO Locations VALUES(97,'The Void Reach',0);
INSERT INTO Locations VALUES(98,'The Winter Territory',2);
INSERT INTO Locations VALUES(99,'Beoxedran',5);
INSERT INTO Locations VALUES(100,'Aefeatuary',0);
INSERT INTO Locations VALUES(101,'Anneagar',3);
INSERT INTO Locations VALUES(102,'Nophudin',4);
INSERT INTO Locations VALUES(103,'Ogetope',3);
INSERT INTO Locations VALUES(104,'The Center Lake',0);
INSERT INTO Locations VALUES(105,'The Shifting Territories',4);
INSERT INTO Locations VALUES(106,'The Ever Moon',1);
INSERT INTO Locations VALUES(107,'The Floating Forest',4);
INSERT INTO Locations VALUES(108,'The Eclipse Domain',5);
INSERT INTO Locations VALUES(109,'Dreattiarath',2);
INSERT INTO Locations VALUES(110,'Eddicyre',2);
INSERT INTO Locations VALUES(111,'Ticcitall',3);
INSERT INTO Locations VALUES(112,'Vaekenet',5);
INSERT INTO Locations VALUES(113,'Tezeorant',1);
INSERT INTO Locations VALUES(114,'The Desolate Nation',2);
INSERT INTO Locations VALUES(115,'The Giant Vales',0);
INSERT INTO Locations VALUES(116,'The Wild World',2);
INSERT INTO Locations VALUES(117,'The Sky Isles',0);
INSERT INTO Locations VALUES(118,'The Fierce Plane',2);
INSERT INTO Locations VALUES(119,'Kriohiorea',1);
INSERT INTO Locations VALUES(120,'Eorrejan',4);
INSERT INTO Locations VALUES(121,'Dreggathaer',3);
INSERT INTO Locations VALUES(122,'Tegruvion',5);
INSERT INTO Locations VALUES(123,'Ocirath',3);
INSERT INTO Locations VALUES(124,'The Shrouded Expanse',3);
INSERT INTO Locations VALUES(125,'The Illusion Empire',1);
INSERT INTO Locations VALUES(126,'The Cerulean Sanctuary',2);
INSERT INTO Locations VALUES(127,'The Utopia Province',2);
INSERT INTO Locations VALUES(128,'The Magic Isle',3);
INSERT INTO Locations VALUES(129,'Uboxar',4);
INSERT INTO Locations VALUES(130,'Adarynn',4);
INSERT INTO Locations VALUES(131,'Feochiomar',1);
INSERT INTO Locations VALUES(132,'Peorialan',0);
INSERT INTO Locations VALUES(133,'Aekkethra',2);
INSERT INTO Locations VALUES(134,'The Glowing Country',5);
INSERT INTO Locations VALUES(135,'The Living Planet',1);
INSERT INTO Locations VALUES(136,'The Past Expanse',0);
INSERT INTO Locations VALUES(137,'The Argent Vale',0);
INSERT INTO Locations VALUES(138,'The Nimbus Lake',5);
INSERT INTO Locations VALUES(139,'Reabreolar',3);
INSERT INTO Locations VALUES(140,'Riaderion',0);
INSERT INTO Locations VALUES(141,'Aeshithaer',1);
INSERT INTO Locations VALUES(142,'Plexetha',5);
INSERT INTO Locations VALUES(143,'Ixagana',2);
INSERT INTO Locations VALUES(144,'The Malachite Nation',1);
INSERT INTO Locations VALUES(145,'The Maroon Reach',2);
INSERT INTO Locations VALUES(146,'The Mythic Country',2);
INSERT INTO Locations VALUES(147,'The Invisible Sanctuary',4);
INSERT INTO Locations VALUES(148,'The Legend Domain',2);
INSERT INTO Locations VALUES(149,'Uppiacion',1);
INSERT INTO Locations VALUES(150,'Aporos',4);
INSERT INTO Locations VALUES(151,'Huqiadalar',0);
INSERT INTO Locations VALUES(152,'Musteqar',2);
INSERT INTO Locations VALUES(153,'Kaenneanet',2);
INSERT INTO Locations VALUES(154,'The Dead Domain',1);
INSERT INTO Locations VALUES(155,'The Cyber Vales',3);
INSERT INTO Locations VALUES(156,'The Pure Sanctuary',4);
INSERT INTO Locations VALUES(157,'The Crimson Reach',2);
INSERT INTO Locations VALUES(158,'The Ancient Dominion',1);
INSERT INTO Locations VALUES(159,'Stiamodalar',3);
INSERT INTO Locations VALUES(160,'Vioppotria',5);
INSERT INTO Locations VALUES(161,'Usseotall',5);
INSERT INTO Locations VALUES(162,'Kraxoxar',0);
INSERT INTO Locations VALUES(163,'Cobedalar',5);
INSERT INTO Locations VALUES(164,'The August Isle',5);
INSERT INTO Locations VALUES(165,'The Sinking Vale',5);
INSERT INTO Locations VALUES(166,'The Ebon Territories',2);
INSERT INTO Locations VALUES(167,'The Regal Fields',2);
INSERT INTO Locations VALUES(168,'The Temporary Fields',0);
INSERT INTO Locations VALUES(169,'Feoneagus',5);
INSERT INTO Locations VALUES(170,'Eokeria',2);
INSERT INTO Locations VALUES(171,'Wriapaterra',4);
INSERT INTO Locations VALUES(172,'Iomuros',1);
INSERT INTO Locations VALUES(173,'Strotathis',5);
INSERT INTO Locations VALUES(174,'The Portal Realm',4);
INSERT INTO Locations VALUES(175,'The Winter Empire',4);
INSERT INTO Locations VALUES(176,'The Jade Territories',0);
INSERT INTO Locations VALUES(177,'The Calm Region',5);
INSERT INTO Locations VALUES(178,'The Hollow Isle',1);
INSERT INTO Locations VALUES(179,'Stonnotuary',3);
INSERT INTO Locations VALUES(180,'Breccearos',0);
INSERT INTO Locations VALUES(181,'Ippugus',2);
INSERT INTO Locations VALUES(182,'Ebbover',5);
INSERT INTO Locations VALUES(183,'Aemmipia',3);
INSERT INTO Locations VALUES(184,'The Peaceful Dominion',3);
INSERT INTO Locations VALUES(185,'The Forsaken Province',0);
INSERT INTO Locations VALUES(186,'The Sky Sea',1);
INSERT INTO Locations VALUES(187,'The Ancient Realms',3);
INSERT INTO Locations VALUES(188,'The Steam Isles',4);
INSERT INTO Locations VALUES(189,'Odadore',2);
INSERT INTO Locations VALUES(190,'Grianixus',2);
INSERT INTO Locations VALUES(191,'Abatora',2);
INSERT INTO Locations VALUES(192,'Wrassiogar',2);
INSERT INTO Locations VALUES(193,'Shobaxar',2);
INSERT INTO Locations VALUES(194,'The Shifting Region',1);
INSERT INTO Locations VALUES(195,'The Mythic Vales',4);
INSERT INTO Locations VALUES(196,'The Nebula Moon',5);
INSERT INTO Locations VALUES(197,'The Enigma Universe',3);
INSERT INTO Locations VALUES(198,'The Abandoned Moon',0);
INSERT INTO Locations VALUES(199,'Qeaddeanem',0);
INSERT INTO Locations VALUES(200,'Claeccenem',4);
INSERT INTO Locations VALUES(201,'Haejisos',1);
INSERT INTO Locations VALUES(202,'Eaddeodalar',0);
INSERT INTO Locations VALUES(203,'Iashadalar',5);
INSERT INTO Locations VALUES(204,'The Steam Vale',2);
INSERT INTO Locations VALUES(205,'The Trial Reach',5);
INSERT INTO Locations VALUES(206,'The Fading Vale',5);
INSERT INTO Locations VALUES(207,'The Fractioned Dominion',3);
INSERT INTO Locations VALUES(208,'The Burning Reach',3);
INSERT INTO Locations VALUES(209,'Lolanica',0);
INSERT INTO Locations VALUES(210,'Laegovion',4);
INSERT INTO Locations VALUES(211,'Ahenara',2);
INSERT INTO Locations VALUES(212,'Aettemar',2);
INSERT INTO Locations VALUES(213,'Peabosia',1);
INSERT INTO Locations VALUES(214,'The Burning World',2);
INSERT INTO Locations VALUES(215,'The Rune Earth',5);
INSERT INTO Locations VALUES(216,'The Black Isle',4);
INSERT INTO Locations VALUES(217,'The Titan Territories',0);
INSERT INTO Locations VALUES(218,'The Imagined Sanctum',3);
INSERT INTO Locations VALUES(219,'Neawudalar',5);
INSERT INTO Locations VALUES(220,'Phaezirus',4);
INSERT INTO Locations VALUES(221,'Vriofexar',5);
INSERT INTO Locations VALUES(222,'Hicholion',0);
INSERT INTO Locations VALUES(223,'Eachalan',1);
INSERT INTO Locations VALUES(224,'The Solar Fields',1);
INSERT INTO Locations VALUES(225,'The Windy Terrain',0);
INSERT INTO Locations VALUES(226,'The Hell Country',2);
INSERT INTO Locations VALUES(227,'The Summer Dominion',1);
INSERT INTO Locations VALUES(228,'The Maroon Planet',1);
INSERT INTO Locations VALUES(229,'Yiaxithra',3);
INSERT INTO Locations VALUES(230,'Ionearona',5);
INSERT INTO Locations VALUES(231,'Roheanara',4);
INSERT INTO Locations VALUES(232,'Ioddathis',1);
INSERT INTO Locations VALUES(233,'Ciakkudalar',5);
INSERT INTO Locations VALUES(234,'The Paralyzed Territory',4);
INSERT INTO Locations VALUES(235,'The Abyss Dominion',3);
INSERT INTO Locations VALUES(236,'The Dragon Expanse',4);
INSERT INTO Locations VALUES(237,'The Storm Province',5);
INSERT INTO Locations VALUES(238,'The Floating Realms',1);
INSERT INTO Locations VALUES(239,'Ufalar',1);
INSERT INTO Locations VALUES(240,'Ziakopia',4);
INSERT INTO Locations VALUES(241,'Bliawetara',0);
INSERT INTO Locations VALUES(242,'Vaeggelar',2);
INSERT INTO Locations VALUES(243,'Emela',5);
INSERT INTO Locations VALUES(244,'The Cinder Realm',1);
INSERT INTO Locations VALUES(245,'The Ever Sea',1);
INSERT INTO Locations VALUES(246,'The God Territories',2);
INSERT INTO Locations VALUES(247,'The Double Moon',5);
INSERT INTO Locations VALUES(248,'The Lonely Plane',4);
INSERT INTO Locations VALUES(249,'Chambers of the Hopeless Cult',5);
INSERT INTO Locations VALUES(250,'Dungeon of the Dishonored Knight',2);
INSERT INTO Locations VALUES(251,'Cells of the Lonely Dragon',0);
INSERT INTO Locations VALUES(252,'Grotto of the Dark Warlord',0);
INSERT INTO Locations VALUES(253,'The Iron Tombs',3);
INSERT INTO Locations VALUES(254,'The Empty Lair',4);
INSERT INTO Locations VALUES(255,'The Dreadful Lair',0);
INSERT INTO Locations VALUES(256,'The Smoky Caverns',5);
INSERT INTO Locations VALUES(257,'The Northern Lair',4);
INSERT INTO Locations VALUES(258,'The Lifeless Labyrinth',5);
INSERT INTO Locations VALUES(259,'Point of the Infernal Morass',2);
INSERT INTO Locations VALUES(260,'Point of the Rejected Army',4);
INSERT INTO Locations VALUES(261,'Maze of the Mourning Warrior',4);
INSERT INTO Locations VALUES(262,'Quarters of the Brutal Basilisk',2);
INSERT INTO Locations VALUES(263,'The Dying Maze',0);
INSERT INTO Locations VALUES(264,'The Unstable Labyrinth',0);
INSERT INTO Locations VALUES(265,'The Mourning Catacombs',5);
INSERT INTO Locations VALUES(266,'The Tormented Grotto',5);
INSERT INTO Locations VALUES(267,'The Sad Vault',0);
INSERT INTO Locations VALUES(268,'The Dire Tunnels',4);
INSERT INTO Locations VALUES(269,'Lair of the Black Desert',4);
INSERT INTO Locations VALUES(270,'Haunt of the Poisoned Jungle',2);
INSERT INTO Locations VALUES(271,'Point of the Frozen Hound',5);
INSERT INTO Locations VALUES(272,'Delves of the Renegade Wizard',1);
INSERT INTO Locations VALUES(273,'The Dream Cells',1);
INSERT INTO Locations VALUES(274,'The Sterile Burrows',4);
INSERT INTO Locations VALUES(275,'The Mesmerizing Dungeon',4);
INSERT INTO Locations VALUES(276,'The Smoldering Quarters',2);
INSERT INTO Locations VALUES(277,'The Arcane Caverns',3);
INSERT INTO Locations VALUES(278,'The Cunning Point',2);
INSERT INTO Locations VALUES(279,'Dungeon of the Shrouded Mountain',2);
INSERT INTO Locations VALUES(280,'Catacombs of the Conquered Giant',2);
INSERT INTO Locations VALUES(281,'Lair of the Impostor Swamp',1);
INSERT INTO Locations VALUES(282,'Catacombs of the Poisoned Queen',1);
INSERT INTO Locations VALUES(283,'The Steel Caverns',5);
INSERT INTO Locations VALUES(284,'The Dread Pits',3);
INSERT INTO Locations VALUES(285,'The Bloodfall Maze',4);
INSERT INTO Locations VALUES(286,'The Vicious Crypt',3);
INSERT INTO Locations VALUES(287,'The Delusion Maze',4);
INSERT INTO Locations VALUES(288,'The Lifeless Tombs',4);
INSERT INTO Locations VALUES(289,'Pits of the Elemental Panther',1);
INSERT INTO Locations VALUES(290,'Tombs of the Golden Priest',0);
INSERT INTO Locations VALUES(291,'Labyrinth of the Rejected Horsemen',0);
INSERT INTO Locations VALUES(292,'Vault of the Shunned Paladin',2);
INSERT INTO Locations VALUES(293,'The Iron Mine Cells',1);
INSERT INTO Locations VALUES(294,'The Full Moon Caverns',3);
INSERT INTO Locations VALUES(295,'The Silent Dungeon',3);
INSERT INTO Locations VALUES(296,'The Living Tombs',1);
INSERT INTO Locations VALUES(297,'The Wondering Burrows',1);
INSERT INTO Locations VALUES(298,'The Howling Delves',0);
INSERT INTO Locations VALUES(299,'Delves of the Ghost Warlord',0);
INSERT INTO Locations VALUES(300,'Labyrinth of the Nightmare Desert',0);
INSERT INTO Locations VALUES(301,'Caverns of the Forsaken Hunter',5);
INSERT INTO Locations VALUES(302,'Point of the Infernal Monk',3);
INSERT INTO Locations VALUES(303,'The White Forest Quarters',4);
INSERT INTO Locations VALUES(304,'The Delusion Quarters',4);
INSERT INTO Locations VALUES(305,'The Erased Cells',5);
INSERT INTO Locations VALUES(306,'The Diamond Catacombs',4);
INSERT INTO Locations VALUES(307,'The Ironbark Quarters',0);
INSERT INTO Locations VALUES(308,'The Dread Grotto',5);
INSERT INTO Locations VALUES(309,'Tombs of the Poisoned Arachnid',0);
INSERT INTO Locations VALUES(310,'Tombs of the Furious Bat',0);
INSERT INTO Locations VALUES(311,'Point of the Burning King',3);
INSERT INTO Locations VALUES(312,'Maze of the Enigmatic Wolf',5);
INSERT INTO Locations VALUES(313,'The Abyss Vault',0);
INSERT INTO Locations VALUES(314,'The Dragontooth Catacombs',0);
INSERT INTO Locations VALUES(315,'The Cursed Crypt',0);
INSERT INTO Locations VALUES(316,'The Burning Forest Chambers',4);
INSERT INTO Locations VALUES(317,'The Hallucination Vault',4);
INSERT INTO Locations VALUES(318,'Dungeon of the Deaths Morass',4);
INSERT INTO Locations VALUES(319,'Dungeon of the Renegade Jungle',0);
INSERT INTO Locations VALUES(320,'Haunt of the Deaths Desert',3);
INSERT INTO Locations VALUES(321,'Chambers of the Raging Mage',2);
INSERT INTO Locations VALUES(322,'The Deep Haunt',3);
INSERT INTO Locations VALUES(323,'The Eternal Crypt',2);
INSERT INTO Locations VALUES(324,'The Scorching Point',0);
INSERT INTO Locations VALUES(325,'The Scheming Burrows',4);
INSERT INTO Locations VALUES(326,'The Sorrow Pits',2);
INSERT INTO Locations VALUES(327,'The Sad Pits',3);
INSERT INTO Locations VALUES(328,'Point of the Vanished Bat',2);
INSERT INTO Locations VALUES(329,'Cells of the Enigmatic Swamp',2);
INSERT INTO Locations VALUES(330,'Catacombs of the Betrayed Forest',2);
INSERT INTO Locations VALUES(331,'Haunt of the Lost Swamp',0);
INSERT INTO Locations VALUES(332,'The Nightmare Burrows',1);
INSERT INTO Locations VALUES(333,'The Oracle Tombs',2);
INSERT INTO Locations VALUES(334,'The Mesmerizing Delves',1);
INSERT INTO Locations VALUES(335,'The Burned Caverns',4);
INSERT INTO Locations VALUES(336,'The Overhanging Caverns',1);
INSERT INTO Locations VALUES(337,'The Twisted Burrows',5);
INSERT INTO Locations VALUES(338,'Caverns of the Silver Legion',1);
INSERT INTO Locations VALUES(339,'Burrows of the Secret Wizard',1);
INSERT INTO Locations VALUES(340,'Burrows of the Dark Goblin',2);
INSERT INTO Locations VALUES(341,'Tombs of the Burning Guardian',0);
INSERT INTO Locations VALUES(342,'The Twilight Cells',2);
INSERT INTO Locations VALUES(343,'The Shadowed Delves',1);
INSERT INTO Locations VALUES(344,'The Flowing Crypt',3);
INSERT INTO Locations VALUES(345,'The Perfumed Grotto',0);
INSERT INTO Locations VALUES(346,'The Violent Point',5);
