INSERT INTO Quests VALUES(0,'The Hate of Pelor',1368);
INSERT INTO Quests VALUES(1,'Beyond Moradins Moore',504);
INSERT INTO Quests VALUES(2,'Knight of the Greedy Valley',154);
INSERT INTO Quests VALUES(3,'The Dead Man Possessed',1116);
INSERT INTO Quests VALUES(4,'Vecnas Fey',587);
INSERT INTO Quests VALUES(5,'Before Erathiss Settlement',1034);
INSERT INTO Quests VALUES(6,'Before the Cruel Caravan',1274);
INSERT INTO Quests VALUES(7,'Drow of the Wicked Temple',795);
INSERT INTO Quests VALUES(8,'General of the Heinous Cage',1237);
INSERT INTO Quests VALUES(9,'The Princess Destiny',1376);
INSERT INTO Quests VALUES(10,'The Corrupt Tomb from Beyond',724);
INSERT INTO Quests VALUES(11,'The Death of Nentir River',460);
INSERT INTO Quests VALUES(12,'Elf of the Fearful Passage',369);
INSERT INTO Quests VALUES(13,'The Magic of Torog',69);
INSERT INTO Quests VALUES(14,'The Fate of Bane',634);
INSERT INTO Quests VALUES(15,'The Wicked Testament from Within',794);
INSERT INTO Quests VALUES(16,'The Tomb Tale',819);
INSERT INTO Quests VALUES(17,'Demonspawn of the Alley',1047);
INSERT INTO Quests VALUES(18,'The Proud Lore Journey',1058);
INSERT INTO Quests VALUES(19,'Pelors Explorer',1198);
INSERT INTO Quests VALUES(20,'Allies of the Underdark',951);
INSERT INTO Quests VALUES(21,'The Conspiracy of The Raven Queen',1272);
INSERT INTO Quests VALUES(22,'Pelors Ghoul',766);
INSERT INTO Quests VALUES(23,'The Stone of Bahamut',169);
INSERT INTO Quests VALUES(24,'The Heinous Barbarian Fate',624);
INSERT INTO Quests VALUES(25,'The Sorcerer Below the Arena',553);
INSERT INTO Quests VALUES(26,'Under the Ailing Mine',1156);
INSERT INTO Quests VALUES(27,'The Gift of Kord',979);
INSERT INTO Quests VALUES(28,'The Wondrous Wand of The Chaos Scar',447);
INSERT INTO Quests VALUES(29,'The Cursed Artifact of The Chaos Scar',340);
INSERT INTO Quests VALUES(30,'Below Moradins Astral Sea',503);
INSERT INTO Quests VALUES(31,'The Charming Revenge from Beyond',1086);
INSERT INTO Quests VALUES(32,'The Wrath of The Raven Queen',369);
INSERT INTO Quests VALUES(33,'Mage of the Tortured Battlefield',1107);
INSERT INTO Quests VALUES(34,'Above the Dungeon',144);
INSERT INTO Quests VALUES(35,'The Journal of Pelor',884);
INSERT INTO Quests VALUES(36,'Through The Raven Queens Hills',596);
INSERT INTO Quests VALUES(37,'The Quest of Ioun',7);
INSERT INTO Quests VALUES(38,'The Witch Below the Fearful Gate',607);
INSERT INTO Quests VALUES(39,'Vecnas Hungering Tribe',54);
INSERT INTO Quests VALUES(40,'Pelors Wondrous Merchant',1155);
INSERT INTO Quests VALUES(41,'Wyvern of the Garden',464);
INSERT INTO Quests VALUES(42,'The Bloodied Daylight from Beyond',532);
INSERT INTO Quests VALUES(43,'The Tortured Ambush Stone',1110);
INSERT INTO Quests VALUES(44,'The Hate of Lake Wintermist',1396);
INSERT INTO Quests VALUES(45,'The Proud Fury Terror',885);
INSERT INTO Quests VALUES(46,'The Mangled Soul Guild',1151);
INSERT INTO Quests VALUES(47,'Torogs Wizard',940);
INSERT INTO Quests VALUES(48,'The Secret Society from Beyond',1208);
INSERT INTO Quests VALUES(49,'Moradins Tortured Queen',1149);
INSERT INTO Quests VALUES(50,'The Proud Witch Ingredient',608);
INSERT INTO Quests VALUES(51,'The Sacred Spy Testament',1008);
INSERT INTO Quests VALUES(52,'The Barter of Vor Rukoth',1390);
INSERT INTO Quests VALUES(53,'The Knight Below the Stream',1004);
INSERT INTO Quests VALUES(54,'The Haunted Ring Legend',415);
INSERT INTO Quests VALUES(55,'The Heinous Worship from Below',241);
INSERT INTO Quests VALUES(56,'Iouns Warlock',640);
INSERT INTO Quests VALUES(57,'The Disappearance of Corellon',816);
INSERT INTO Quests VALUES(58,'The Damned Below the Fleeting Maze',65);
INSERT INTO Quests VALUES(59,'The Traveler Heirloom',1214);
INSERT INTO Quests VALUES(60,'The Monk Above the Traitorous Dungeon',1039);
INSERT INTO Quests VALUES(61,'The Greedy Wyvern Fear',983);
INSERT INTO Quests VALUES(62,'The Companionship of Torog',665);
INSERT INTO Quests VALUES(63,'The Key of The Witchlight Fens',1264);
INSERT INTO Quests VALUES(64,'Within Pelors Labyrinth',1129);
INSERT INTO Quests VALUES(65,'The Journey from Beyond',793);
INSERT INTO Quests VALUES(66,'Iouns Master',165);
INSERT INTO Quests VALUES(67,'Through the Heinous Feywild',816);
INSERT INTO Quests VALUES(68,'The Raven Queens Witness',757);
INSERT INTO Quests VALUES(69,'The Fleeting Circle from Beyond',1148);
INSERT INTO Quests VALUES(70,'Through Orcuss Stockade',1116);
INSERT INTO Quests VALUES(71,'The Abandoned Triumph from Beyond',812);
INSERT INTO Quests VALUES(72,'The Menacing Plague Lance',1204);
INSERT INTO Quests VALUES(73,'The Mangled Horror from Above',323);
INSERT INTO Quests VALUES(74,'The Heinous Lance Sorrow',306);
INSERT INTO Quests VALUES(75,'Beyond Corellons Coast',1220);
INSERT INTO Quests VALUES(76,'The Wondrous Puzzle from Beyond',1113);
INSERT INTO Quests VALUES(77,'Above The Raven Queens Castle',449);
INSERT INTO Quests VALUES(78,'The Summer of Gruumsh',1090);
INSERT INTO Quests VALUES(79,'The Broken Barter from Beyond',1340);
INSERT INTO Quests VALUES(80,'The Scourge Mystery',1034);
INSERT INTO Quests VALUES(81,'The General Potion',512);
INSERT INTO Quests VALUES(82,'Before the Tomb',714);
INSERT INTO Quests VALUES(83,'The Foe Above the Inn',1406);
INSERT INTO Quests VALUES(84,'Banes Abandoned Dead Man',1394);
INSERT INTO Quests VALUES(85,'Explorer of the Fair',926);
INSERT INTO Quests VALUES(86,'The Vanishing Gang from Within',837);
INSERT INTO Quests VALUES(87,'Across the Library',886);
INSERT INTO Quests VALUES(88,'Below Gruumshs Market',1395);
INSERT INTO Quests VALUES(89,'Erathiss Fearful Men',338);
INSERT INTO Quests VALUES(90,'Rider of the Mine',1081);
INSERT INTO Quests VALUES(91,'The Wand of Winterhaven',901);
INSERT INTO Quests VALUES(92,'Gruumshs Dragon',1087);
INSERT INTO Quests VALUES(93,'Bahamuts Vengeful General',579);
INSERT INTO Quests VALUES(94,'The Haunted Mage Silver',1271);
INSERT INTO Quests VALUES(95,'The Fury from Above',176);
INSERT INTO Quests VALUES(96,'The Murderous Faction from Above',336);
INSERT INTO Quests VALUES(97,'Corellons Living Dead',49);
INSERT INTO Quests VALUES(98,'The Disappearance of Erathis',637);
INSERT INTO Quests VALUES(99,'The Trick of Orcus',1373);
INSERT INTO Quests VALUES(100,'The Follower Within the Stout Town',1125);
INSERT INTO Quests VALUES(101,'The Cursed Cloak from Above',759);
INSERT INTO Quests VALUES(102,'Below the Sticky Theater',1011);
INSERT INTO Quests VALUES(103,'The Allies Above the Alley',101);
INSERT INTO Quests VALUES(104,'Banes Dwarf',96);
INSERT INTO Quests VALUES(105,'Moradins Murderous Knight',1363);
INSERT INTO Quests VALUES(106,'The Last Militia of Ogrefist Hills',1108);
INSERT INTO Quests VALUES(107,'Across Vecnas Circus',570);
INSERT INTO Quests VALUES(108,'Above the Greedy Festival',1174);
INSERT INTO Quests VALUES(109,'Below the Scorched Caravan',673);
INSERT INTO Quests VALUES(110,'The Mourning of Orcus',1016);
INSERT INTO Quests VALUES(111,'The Plagued Song Exploration',1398);
INSERT INTO Quests VALUES(112,'The Verse of Corellon',1106);
INSERT INTO Quests VALUES(113,'Within Kords Castle',70);
INSERT INTO Quests VALUES(114,'The Crops of Bane',707);
INSERT INTO Quests VALUES(115,'The Mercenary Above the Scorched Stockade',1350);
INSERT INTO Quests VALUES(116,'The Diary from Within',228);
INSERT INTO Quests VALUES(117,'The Monstrous Legend Wager',584);
INSERT INTO Quests VALUES(118,'The Menacing Winter of Nenlast',1104);
INSERT INTO Quests VALUES(119,'The Mount of Winterbole Forest',446);
INSERT INTO Quests VALUES(120,'The Fading Arrow from Below',1003);
INSERT INTO Quests VALUES(121,'The Traitorous Scourge from Within',1304);
INSERT INTO Quests VALUES(122,'The Merchant Above the Home',22);
INSERT INTO Quests VALUES(123,'Through Gruumshs Necropolis',1017);
INSERT INTO Quests VALUES(124,'The Altar Lure',174);
INSERT INTO Quests VALUES(125,'The Laughing Rider Punishment',241);
INSERT INTO Quests VALUES(126,'The Squire Above the Halls',81);
INSERT INTO Quests VALUES(127,'The Wolf Wrath',924);
INSERT INTO Quests VALUES(128,'Torogs Fiery Peasant',1079);
INSERT INTO Quests VALUES(129,'The Beholder Trap',905);
INSERT INTO Quests VALUES(130,'The Faction Waste',162);
INSERT INTO Quests VALUES(131,'Below Bahamuts Great Sea',727);
INSERT INTO Quests VALUES(132,'Beyond the Lovable Passage',319);
INSERT INTO Quests VALUES(133,'The Corrupt Whisper of Nentir River',621);
INSERT INTO Quests VALUES(134,'Above the Vengeful Stream',256);
INSERT INTO Quests VALUES(135,'Across the Fleeting Caravan',155);
INSERT INTO Quests VALUES(136,'Demonspawn of the Gate',963);
INSERT INTO Quests VALUES(137,'The Wand of The Raven Queen',1090);
INSERT INTO Quests VALUES(138,'The Altar of Erathis',605);
INSERT INTO Quests VALUES(139,'Before the Monstrous Mountain',1017);
INSERT INTO Quests VALUES(140,'Within Erathiss Coast',1026);
INSERT INTO Quests VALUES(141,'The Rider Below the Dying Library',664);
INSERT INTO Quests VALUES(142,'Through the Moore',1320);
INSERT INTO Quests VALUES(143,'The Nightmare of The Raven Queen',1189);
INSERT INTO Quests VALUES(144,'The Demon Ring',202);
INSERT INTO Quests VALUES(145,'Across Banes Mountain',485);
INSERT INTO Quests VALUES(146,'Kords Fey',1308);
INSERT INTO Quests VALUES(147,'The Portal of The Dawnforge Mountains',1083);
INSERT INTO Quests VALUES(148,'Orcuss Forgotten Demon',390);
INSERT INTO Quests VALUES(149,'Erathiss Dragon',1248);
INSERT INTO Quests VALUES(150,'Beyond the Dungeon',236);
INSERT INTO Quests VALUES(151,'The Raven Queens Brave Barbarian',501);
INSERT INTO Quests VALUES(152,'The Master Below the Town',742);
INSERT INTO Quests VALUES(153,'The Slaad Above the Plagued Gate',1054);
INSERT INTO Quests VALUES(154,'Under Erathiss Badlands',1360);
INSERT INTO Quests VALUES(155,'Above the Island',1222);
INSERT INTO Quests VALUES(156,'The Exarch Militia',177);
INSERT INTO Quests VALUES(157,'The Terrible Siege Blaze',242);
INSERT INTO Quests VALUES(158,'Before the Elemental Chaos',1221);
INSERT INTO Quests VALUES(159,'Under the Lake',1055);
INSERT INTO Quests VALUES(160,'The Murderous Jewel from Above',1201);
INSERT INTO Quests VALUES(161,'The Diary Nightmare',110);
INSERT INTO Quests VALUES(162,'The Tortured Blaze Trade',844);
INSERT INTO Quests VALUES(163,'The Quest from Within',856);
INSERT INTO Quests VALUES(164,'The Powerful Messenger Worship',1059);
INSERT INTO Quests VALUES(165,'The Wand of Orcus',895);
INSERT INTO Quests VALUES(166,'The Wolf Below the Lingering Bridge',1127);
INSERT INTO Quests VALUES(167,'The Restless Mist from Beyond',614);
INSERT INTO Quests VALUES(168,'Troll of the Murderous Coast',269);
INSERT INTO Quests VALUES(169,'The Wailing Exploration Fall',227);
INSERT INTO Quests VALUES(170,'The Fear of Gruumsh',749);
INSERT INTO Quests VALUES(171,'Through Orcuss Grove',1239);
INSERT INTO Quests VALUES(172,'The Fleeting Book from Below',48);
INSERT INTO Quests VALUES(173,'The Scorched Mist Trap',1080);
INSERT INTO Quests VALUES(174,'Across Banes Desert',1317);
INSERT INTO Quests VALUES(175,'Iouns Fleeting Hero',1239);
INSERT INTO Quests VALUES(176,'The Weakness Power',938);
INSERT INTO Quests VALUES(177,'The Lich Within the Worlds',62);
INSERT INTO Quests VALUES(178,'Beyond Erathiss Coast',173);
INSERT INTO Quests VALUES(179,'Before Erathiss Catacombs',154);
INSERT INTO Quests VALUES(180,'Above the Terrible Harbor',1283);
INSERT INTO Quests VALUES(181,'Within Vecnas Woods',969);
INSERT INTO Quests VALUES(182,'Iouns Final Corpse',396);
INSERT INTO Quests VALUES(183,'The Deathly Bribe from Below',274);
INSERT INTO Quests VALUES(184,'The Heinous Silver from Beyond',742);
INSERT INTO Quests VALUES(185,'Across the Hamlet',63);
INSERT INTO Quests VALUES(186,'The Exploration from Below',1034);
INSERT INTO Quests VALUES(187,'Gnoll of the Grove',1134);
INSERT INTO Quests VALUES(188,'Erathiss Warlock',1410);
INSERT INTO Quests VALUES(189,'The Locket of Trade Road',1105);
INSERT INTO Quests VALUES(190,'Follower of the Hungering Woods',1410);
INSERT INTO Quests VALUES(191,'The Broken Beholder Riddles',1300);
INSERT INTO Quests VALUES(192,'The Heart of Vecna',13);
INSERT INTO Quests VALUES(193,'Pelors Queen',1128);
INSERT INTO Quests VALUES(194,'Before the Fiery Cavern',261);
INSERT INTO Quests VALUES(195,'The Gnoll Fall',1116);
INSERT INTO Quests VALUES(196,'Before the Stockade',223);
INSERT INTO Quests VALUES(197,'Below the Strong Cage',1140);
INSERT INTO Quests VALUES(198,'Banes Menacing Slave',1021);
INSERT INTO Quests VALUES(199,'Kords Wealthy Child',651);
INSERT INTO Quests VALUES(200,'The Summer Legend',332);
INSERT INTO Quests VALUES(201,'The Companionship of The Witchlight Fens',1313);
INSERT INTO Quests VALUES(202,'Gruumshs Ailing Monk',1115);
INSERT INTO Quests VALUES(203,'Blacksmith of the Murderous Battlefield',108);
INSERT INTO Quests VALUES(204,'Through Gruumshs Realm',521);
INSERT INTO Quests VALUES(205,'Below the Badlands',5);
INSERT INTO Quests VALUES(206,'The Portal Blade',930);
INSERT INTO Quests VALUES(207,'Corellons Vengeful Demon',67);
INSERT INTO Quests VALUES(208,'The Promise from Above',195);
INSERT INTO Quests VALUES(209,'Foe of the Cliff',22);
INSERT INTO Quests VALUES(210,'The Careless Storm of Nenlast',936);
INSERT INTO Quests VALUES(211,'The Riddles Journal',1385);
INSERT INTO Quests VALUES(212,'The Spider Shield',969);
INSERT INTO Quests VALUES(213,'The Drow End',697);
INSERT INTO Quests VALUES(214,'Rakshasa of the Underground',465);
INSERT INTO Quests VALUES(215,'The Cursed Goblin Gallows',894);
INSERT INTO Quests VALUES(216,'The Journey from Below',413);
INSERT INTO Quests VALUES(217,'Within Erathiss Grove',1260);
INSERT INTO Quests VALUES(218,'Slaver of the Necropolis',1317);
INSERT INTO Quests VALUES(219,'The Sticky Vampire Farewell',714);
INSERT INTO Quests VALUES(220,'Kords Tamer',312);
INSERT INTO Quests VALUES(221,'The Army of The Raven Queen',251);
INSERT INTO Quests VALUES(222,'Demon of the Hollow Tomb',541);
INSERT INTO Quests VALUES(223,'The Ambush of Vecna',68);
INSERT INTO Quests VALUES(224,'The Forgotten Death of Lake Nen',587);
INSERT INTO Quests VALUES(225,'Within the Circus',96);
INSERT INTO Quests VALUES(226,'Gruumshs Warrior',471);
INSERT INTO Quests VALUES(227,'The Corrupt Whisper from Beyond',471);
INSERT INTO Quests VALUES(228,'The Wailing Reckoning from Below',185);
INSERT INTO Quests VALUES(229,'The Greedy Wyvern Dream',659);
INSERT INTO Quests VALUES(230,'The Terror of Lake Nen',951);
INSERT INTO Quests VALUES(231,'Moradins Wyvern',1352);
INSERT INTO Quests VALUES(232,'Beyond Bahamuts Badlands',490);
INSERT INTO Quests VALUES(233,'Below the Planes',1217);
INSERT INTO Quests VALUES(234,'The Drum of Bahamut',98);
INSERT INTO Quests VALUES(235,'The Drow Beyond the Abandoned Town',1135);
INSERT INTO Quests VALUES(236,'The Lore from Within',1168);
INSERT INTO Quests VALUES(237,'The Confession of Winterhaven',949);
INSERT INTO Quests VALUES(238,'Above the Evil River',763);
INSERT INTO Quests VALUES(239,'The Damned Within the Last Jail',759);
INSERT INTO Quests VALUES(240,'The Laughing Jewel Expedition',34);
INSERT INTO Quests VALUES(241,'The Menacing Scheme from Below',369);
INSERT INTO Quests VALUES(242,'Before the Gate',313);
INSERT INTO Quests VALUES(243,'Adventurer of the Swamp',286);
INSERT INTO Quests VALUES(244,'Gruumshs Blacksmith',1063);
INSERT INTO Quests VALUES(245,'Orcuss Tribe',389);
INSERT INTO Quests VALUES(246,'The Death Treason',1249);
INSERT INTO Quests VALUES(247,'The Worship of Pelor',512);
INSERT INTO Quests VALUES(248,'Gnoll of the Broken Desert',1030);
INSERT INTO Quests VALUES(249,'Before Iouns Sea',1311);
INSERT INTO Quests VALUES(250,'The Wrath Blade',302);
INSERT INTO Quests VALUES(251,'The Warlord Below the Sea',1137);
INSERT INTO Quests VALUES(252,'Through the Blind Hamlet',275);
INSERT INTO Quests VALUES(253,'The God Within the Menacing Woods',226);
INSERT INTO Quests VALUES(254,'The Hero Above the Garden',960);
INSERT INTO Quests VALUES(255,'Above the Astral Sea',505);
INSERT INTO Quests VALUES(256,'The Laughing Confession Conspiracy',1376);
INSERT INTO Quests VALUES(257,'The Rage from Above',708);
INSERT INTO Quests VALUES(258,'The Stone of Torog',256);
INSERT INTO Quests VALUES(259,'Within Corellons Island',566);
INSERT INTO Quests VALUES(260,'The Grave Wager',218);
INSERT INTO Quests VALUES(261,'Under Erathiss Cliff',1156);
INSERT INTO Quests VALUES(262,'The Barter from Above',304);
INSERT INTO Quests VALUES(263,'Orcuss Fleeting Vampire',883);
INSERT INTO Quests VALUES(264,'The Sisters Below the Final Keep',311);
INSERT INTO Quests VALUES(265,'Within the Strong Tomb',547);
INSERT INTO Quests VALUES(266,'Marksman of the Valley',2);
INSERT INTO Quests VALUES(267,'Within the Monstrous Fair',1316);
INSERT INTO Quests VALUES(268,'The Ailing Wall Arrow',1075);
INSERT INTO Quests VALUES(269,'The Fading Trouble from Beyond',952);
INSERT INTO Quests VALUES(270,'The Hero Arrow',651);
INSERT INTO Quests VALUES(271,'The Wolf Exploration',610);
INSERT INTO Quests VALUES(272,'The Wondrous Heart Confession',1333);
INSERT INTO Quests VALUES(273,'Bahamuts Forgotten Widow',269);
INSERT INTO Quests VALUES(274,'The Evil Ingredient from Beyond',495);
INSERT INTO Quests VALUES(275,'The Winter from Within',1147);
INSERT INTO Quests VALUES(276,'Above Bahamuts Gate',956);
INSERT INTO Quests VALUES(277,'The Slaver Below the Home',270);
INSERT INTO Quests VALUES(278,'Above the Terrible Cage',788);
INSERT INTO Quests VALUES(279,'The Artifact of Nentir River',1407);
INSERT INTO Quests VALUES(280,'The Assassin Within the House',556);
INSERT INTO Quests VALUES(281,'Above Gruumshs Tower',850);
INSERT INTO Quests VALUES(282,'Banes Tortured Squire',227);
INSERT INTO Quests VALUES(283,'The Orb of Corellon',622);
INSERT INTO Quests VALUES(284,'The Widow Beyond the Halls',1311);
INSERT INTO Quests VALUES(285,'The Portal of Bane',53);
INSERT INTO Quests VALUES(286,'Under the City',728);
INSERT INTO Quests VALUES(287,'The Justice Locket',1072);
INSERT INTO Quests VALUES(288,'The Demonspawn Ritual',378);
INSERT INTO Quests VALUES(289,'The Defeat of Orcus',289);
INSERT INTO Quests VALUES(290,'The Sticky Drum of Winterbole Forest',250);
INSERT INTO Quests VALUES(291,'The Lich Beyond the Garden',1327);
INSERT INTO Quests VALUES(292,'Iouns Guilty',1186);
INSERT INTO Quests VALUES(293,'The Cruel Sword of Sigil',453);
INSERT INTO Quests VALUES(294,'The Symbol of Nentir Vale',655);
INSERT INTO Quests VALUES(295,'Across the Stout Worlds',1326);
INSERT INTO Quests VALUES(296,'Lost of the Theater',1148);
INSERT INTO Quests VALUES(297,'Torogs Traveling Warlord',1019);
INSERT INTO Quests VALUES(298,'The Barbarian Beyond the Portal',337);
INSERT INTO Quests VALUES(299,'The Murder from Beyond',758);
INSERT INTO Quests VALUES(300,'The Forgotten Spell from Beyond',126);
INSERT INTO Quests VALUES(301,'Above the Sacred Mine',937);
INSERT INTO Quests VALUES(302,'Gnoll of the Hillside',186);
INSERT INTO Quests VALUES(303,'The Last Stand of Nenlast',897);
INSERT INTO Quests VALUES(304,'The Lore Trap',14);
INSERT INTO Quests VALUES(305,'The Wyvern Justice',1064);
INSERT INTO Quests VALUES(306,'The Traveling Curse from Beyond',265);
INSERT INTO Quests VALUES(307,'The Corpse Within the Cruel Grave',1069);
INSERT INTO Quests VALUES(308,'The Crown of Kord',758);
INSERT INTO Quests VALUES(309,'The Father of Vor Rukoth',857);
INSERT INTO Quests VALUES(310,'The Rage of Gruumsh',926);
INSERT INTO Quests VALUES(311,'Outlaw of the Mangled Swamp',562);
INSERT INTO Quests VALUES(312,'Below the Dying Island',460);
INSERT INTO Quests VALUES(313,'Across The Raven Queens Woods',247);
INSERT INTO Quests VALUES(314,'Angel of the Cave',879);
INSERT INTO Quests VALUES(315,'The Cruel Strength from Above',790);
INSERT INTO Quests VALUES(316,'The Laughing Silver of The Witchlight Fens',869);
INSERT INTO Quests VALUES(317,'Pelors Careless Orc',467);
INSERT INTO Quests VALUES(318,'The Sacred Scourge of Harkenwold',1248);
INSERT INTO Quests VALUES(319,'Beyond the Restless Cavern',1121);
INSERT INTO Quests VALUES(320,'Spirit of the House',149);
INSERT INTO Quests VALUES(321,'The Gold of Bahamut',1153);
INSERT INTO Quests VALUES(322,'The Menacing Jewel from Above',1072);
INSERT INTO Quests VALUES(323,'The Bard Tale',475);
INSERT INTO Quests VALUES(324,'The Unspeakable Spy Terror',1054);
INSERT INTO Quests VALUES(325,'The Trade Wall',916);
INSERT INTO Quests VALUES(326,'The Monstrous Breath Circle',1374);
INSERT INTO Quests VALUES(327,'Vecnas Zombie',237);
INSERT INTO Quests VALUES(328,'The Secret Society of Orcus',133);
INSERT INTO Quests VALUES(329,'The Punishment of Torog',785);
INSERT INTO Quests VALUES(330,'The Scroll of Gray Downs',992);
INSERT INTO Quests VALUES(331,'The Elf Locket',1282);
INSERT INTO Quests VALUES(332,'Pelors Fading Hero',1102);
INSERT INTO Quests VALUES(333,'Before the Garden',371);
INSERT INTO Quests VALUES(334,'Kords Wailing Exarch',261);
INSERT INTO Quests VALUES(335,'The Orc Sword',202);
INSERT INTO Quests VALUES(336,'Through the Market',989);
INSERT INTO Quests VALUES(337,'The Mangled Bribe of Nentir River',940);
INSERT INTO Quests VALUES(338,'Lost of the Time',87);
INSERT INTO Quests VALUES(339,'Before the Mountain',474);
INSERT INTO Quests VALUES(340,'The Mount of Kord',244);
INSERT INTO Quests VALUES(341,'The Expedition of Corellon',1238);
INSERT INTO Quests VALUES(342,'The Charming Ritual Cult',820);
INSERT INTO Quests VALUES(343,'The Treason of Torog',442);
INSERT INTO Quests VALUES(344,'Widow of the Cliff',628);
INSERT INTO Quests VALUES(345,'The Trouble of Gruumsh',61);
INSERT INTO Quests VALUES(346,'The Wolf Legend',468);
INSERT INTO Quests VALUES(347,'Men of the Fair',77);
INSERT INTO Quests VALUES(348,'The Expedition from Within',1344);
INSERT INTO Quests VALUES(349,'The Fleeting Order of Hammerfast',908);
INSERT INTO Quests VALUES(350,'The Lore from Above',658);
INSERT INTO Quests VALUES(351,'Outlaw of the Dungeon',14);
INSERT INTO Quests VALUES(352,'Above the Charming Great Sea',352);
INSERT INTO Quests VALUES(353,'The Siege of Vecna',1284);
INSERT INTO Quests VALUES(354,'The Vampire Within the House',54);
INSERT INTO Quests VALUES(355,'Across the Elemental Chaos',922);
INSERT INTO Quests VALUES(356,'The Burning of Nentir Vale',1388);
INSERT INTO Quests VALUES(357,'The Menacing Poison Altar',327);
INSERT INTO Quests VALUES(358,'Assassin of the Hollow Caravan',127);
INSERT INTO Quests VALUES(359,'The Crown of Ogrefist Hills',1073);
INSERT INTO Quests VALUES(360,'Under Iouns Moore',534);
INSERT INTO Quests VALUES(361,'The Cult of Pelor',641);
INSERT INTO Quests VALUES(362,'The Ailing Lycanthrope Magic',878);
INSERT INTO Quests VALUES(363,'Vecnas Warlock',1376);
INSERT INTO Quests VALUES(364,'The Exarch Disappearance',533);
INSERT INTO Quests VALUES(365,'Banes Lovable Wyvern',98);
INSERT INTO Quests VALUES(366,'Below the Blind Desert',465);
INSERT INTO Quests VALUES(367,'The Lore of The Dawnforge Mountains',512);
INSERT INTO Quests VALUES(368,'The Final Hero Siege',1153);
INSERT INTO Quests VALUES(369,'Bahamuts Messenger',1333);
INSERT INTO Quests VALUES(370,'The Faction of Corellon',968);
INSERT INTO Quests VALUES(371,'The Drow Below the Lake',185);
INSERT INTO Quests VALUES(372,'The Outlaw Ring',670);
INSERT INTO Quests VALUES(373,'Messenger of the Abandoned Tavern',537);
INSERT INTO Quests VALUES(374,'The Queen Within the Halls',560);
INSERT INTO Quests VALUES(375,'The Spider Journey',1158);
INSERT INTO Quests VALUES(376,'The Last Stand from Beyond',965);
INSERT INTO Quests VALUES(377,'Wolf of the Fair',1069);
INSERT INTO Quests VALUES(378,'The Explorer Beyond the Tavern',751);
INSERT INTO Quests VALUES(379,'Above the Scorched Carnival',185);
INSERT INTO Quests VALUES(380,'Above the Sacred Cliff',942);
INSERT INTO Quests VALUES(381,'Vecnas God',1216);
INSERT INTO Quests VALUES(382,'Iouns Sticky Beholder',1203);
INSERT INTO Quests VALUES(383,'The Fearful Sorrow of Winterhaven',1305);
INSERT INTO Quests VALUES(384,'The Blacksmith Below the Arena',1374);
INSERT INTO Quests VALUES(385,'The Punishment Gift',91);
INSERT INTO Quests VALUES(386,'The Puzzle of Orcus',378);
INSERT INTO Quests VALUES(387,'Living Dead of the Marshes',927);
INSERT INTO Quests VALUES(388,'Beyond Iouns Hillside',1191);
INSERT INTO Quests VALUES(389,'Before the Traveling Jail',982);
INSERT INTO Quests VALUES(390,'The Explorer Within the Haunted Festival',1120);
INSERT INTO Quests VALUES(391,'The Ranger Beyond the Vanishing Shadowfell',715);
INSERT INTO Quests VALUES(392,'Above Pelors Land',673);
INSERT INTO Quests VALUES(393,'Kords Strong Adventurer',1393);
INSERT INTO Quests VALUES(394,'Through Erathiss Kingdom',863);
INSERT INTO Quests VALUES(395,'The Lure of Winterbole Forest',629);
INSERT INTO Quests VALUES(396,'Before the Cave',133);
INSERT INTO Quests VALUES(397,'Erathiss Heinous Bard',1318);
INSERT INTO Quests VALUES(398,'The Witch Below the Traitorous Swamp',1278);
INSERT INTO Quests VALUES(399,'Courier of the Plagued Lake',198);
INSERT INTO Quests VALUES(400,'Through the Hungering Island',743);
INSERT INTO Quests VALUES(401,'The Fading Conspiracy of Sigil',334);
INSERT INTO Quests VALUES(402,'Vampire of the Fearful Ship',1107);
INSERT INTO Quests VALUES(403,'Blacksmith of the Maze',876);
INSERT INTO Quests VALUES(404,'Across Kords Village',546);
INSERT INTO Quests VALUES(405,'Before the Inn',684);
INSERT INTO Quests VALUES(406,'The Warlock Below the Labyrinth',741);
INSERT INTO Quests VALUES(407,'The Trouble Last Stand',1061);
INSERT INTO Quests VALUES(408,'The Crown of Moradin',371);
INSERT INTO Quests VALUES(409,'The Blade from Within',152);
INSERT INTO Quests VALUES(410,'The Prophecy of Kord',1308);
INSERT INTO Quests VALUES(411,'The Stout Crown from Beyond',77);
INSERT INTO Quests VALUES(412,'The Widow Below the Home',1354);
INSERT INTO Quests VALUES(413,'Beyond the Garden',505);
INSERT INTO Quests VALUES(414,'Wizard of the Scorched Great Sea',489);
INSERT INTO Quests VALUES(415,'The Exarch Below the Carnival',113);
INSERT INTO Quests VALUES(416,'Above Banes Temple',464);
INSERT INTO Quests VALUES(417,'The Map from Above',398);
INSERT INTO Quests VALUES(418,'The Widow Rage',846);
INSERT INTO Quests VALUES(419,'Spy of the Vile Isle',831);
INSERT INTO Quests VALUES(420,'Above the Broken Library',703);
INSERT INTO Quests VALUES(421,'Beyond the Mind',1393);
INSERT INTO Quests VALUES(422,'Orcuss Abandoned God',152);
INSERT INTO Quests VALUES(423,'The Fey Blade',846);
INSERT INTO Quests VALUES(424,'The Slave Above the Passage',675);
INSERT INTO Quests VALUES(425,'Across the Lake',746);
INSERT INTO Quests VALUES(426,'The Soldier Above the Library',762);
INSERT INTO Quests VALUES(427,'Above the Abandoned Moore',1312);
INSERT INTO Quests VALUES(428,'Hero of the Traitorous Necropolis',591);
INSERT INTO Quests VALUES(429,'The Merchant Within the Wondrous Great Sea',467);
INSERT INTO Quests VALUES(430,'The Trick Gallows',502);
INSERT INTO Quests VALUES(431,'The Aberration Within the Dying Labyrinth',118);
INSERT INTO Quests VALUES(432,'Corellons Blind Myconid',297);
INSERT INTO Quests VALUES(433,'Messenger of the Hungering Bridge',40);
INSERT INTO Quests VALUES(434,'Kords Myconid',1023);
INSERT INTO Quests VALUES(435,'The Disappearance of Nentir River',287);
INSERT INTO Quests VALUES(436,'Torogs Hero',793);
INSERT INTO Quests VALUES(437,'The Final Fear from Below',1030);
INSERT INTO Quests VALUES(438,'The Wondrous Bargain from Beyond',604);
INSERT INTO Quests VALUES(439,'The Map Cloak',223);
INSERT INTO Quests VALUES(440,'The Bloodied Wager of Trade Road',69);
INSERT INTO Quests VALUES(441,'Below the Catacombs',1063);
INSERT INTO Quests VALUES(442,'Exarch of the Cave',747);
INSERT INTO Quests VALUES(443,'The Brave Harvest from Beyond',576);
INSERT INTO Quests VALUES(444,'Before Orcuss Ship',496);
INSERT INTO Quests VALUES(445,'The Scepter of Winterhaven',1407);
INSERT INTO Quests VALUES(446,'Before Moradins Carnival',776);
INSERT INTO Quests VALUES(447,'The Follower Below the Woods',264);
INSERT INTO Quests VALUES(448,'Iouns Drow',1336);
INSERT INTO Quests VALUES(449,'General of the Lovable Dungeon',148);
INSERT INTO Quests VALUES(450,'Beyond Moradins Cage',606);
INSERT INTO Quests VALUES(451,'Spy of the Elemental Chaos',1142);
INSERT INTO Quests VALUES(452,'The Plague from Within',1261);
INSERT INTO Quests VALUES(453,'Under Orcuss Circus',1206);
INSERT INTO Quests VALUES(454,'Torogs Wealthy Spider',908);
INSERT INTO Quests VALUES(455,'The Troll Below the Land',379);
INSERT INTO Quests VALUES(456,'Iouns Mangled Assassin',326);
INSERT INTO Quests VALUES(457,'Across Orcuss Great Sea',1158);
INSERT INTO Quests VALUES(458,'Orcuss Restless Goblin',1289);
INSERT INTO Quests VALUES(459,'Pelors Powerful Barbarian',985);
INSERT INTO Quests VALUES(460,'Under Banes Fair',1203);
INSERT INTO Quests VALUES(461,'Bahamuts Dying Follower',472);
INSERT INTO Quests VALUES(462,'Rider of the Evil Tower',96);
INSERT INTO Quests VALUES(463,'The Warlord Siege',1008);
INSERT INTO Quests VALUES(464,'The Murderous Warlock Cloak',300);
INSERT INTO Quests VALUES(465,'The Brothers Within the Underground',1014);
INSERT INTO Quests VALUES(466,'Exarch of the Caravan',107);
INSERT INTO Quests VALUES(467,'The Crown of Harkenwold',586);
INSERT INTO Quests VALUES(468,'Erathiss Ailing Fey',582);
INSERT INTO Quests VALUES(469,'Iouns Elf',211);
INSERT INTO Quests VALUES(470,'The Blade of Gray Downs',30);
INSERT INTO Quests VALUES(471,'Before Banes Castle',984);
INSERT INTO Quests VALUES(472,'The Vanishing Darkness Legend',897);
INSERT INTO Quests VALUES(473,'Within Moradins Tomb',533);
INSERT INTO Quests VALUES(474,'The Crown of Orcus',1224);
INSERT INTO Quests VALUES(475,'Through the Shadowfell',130);
INSERT INTO Quests VALUES(476,'Moradins Sticky Princess',464);
INSERT INTO Quests VALUES(477,'Below the Garden',108);
INSERT INTO Quests VALUES(478,'The Crown Quest',314);
INSERT INTO Quests VALUES(479,'The Lost Beyond the Hamlet',1288);
INSERT INTO Quests VALUES(480,'Elf of the Portal',1309);
INSERT INTO Quests VALUES(481,'Before the Deathly Kingdom',10);
INSERT INTO Quests VALUES(482,'The Sorcerer Map',713);
INSERT INTO Quests VALUES(483,'The Sorrow of Vecna',834);
INSERT INTO Quests VALUES(484,'The Gith Beyond the Kingdom',1143);
INSERT INTO Quests VALUES(485,'Messenger of the Underdark',650);
INSERT INTO Quests VALUES(486,'The Zombie Above the Passage',1268);
INSERT INTO Quests VALUES(487,'The Sword of Gruumsh',1147);
INSERT INTO Quests VALUES(488,'The Murderous Cult from Beyond',755);
INSERT INTO Quests VALUES(489,'Above the Wealthy Tavern',860);
INSERT INTO Quests VALUES(490,'The Fey Below the Ship',920);
INSERT INTO Quests VALUES(491,'The Drum from Within',288);
INSERT INTO Quests VALUES(492,'Below the Fleeting Mind',1108);
INSERT INTO Quests VALUES(493,'The Traitorous Lance of Nentir Vale',1258);
INSERT INTO Quests VALUES(494,'The Powerful Soul Curse',1121);
INSERT INTO Quests VALUES(495,'The Mangled Lore of Sigil',448);
INSERT INTO Quests VALUES(496,'The Wager from Within',1335);
INSERT INTO Quests VALUES(497,'Within the Lake',467);
INSERT INTO Quests VALUES(498,'Erathiss Wealthy Brothers',1405);
INSERT INTO Quests VALUES(499,'Below Erathiss Planes',540);
